# Generated by Django 4.2.3 on 2023-07-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(max_length=1),
        ),
    ]
