# Generated by Django 4.2.3 on 2023-07-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertasks', '0002_alter_tasks_priority_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dueDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
